version: "1"
services:
       manager:
           container_name: manager
           image: manager
           restart: always
           build: .
           ports:
             - "5001:5001"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'